import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "About — Istanbul Restaurants",
  description:
    "What is Istanbul Restaurants, how is the data collected, and which sources are used? Methodology and reliability of our Istanbul restaurant database.",
  alternates: { canonical: "https://restaurantsistanbul.vercel.app/hakkinda" },
  openGraph: {
    title: "About — Istanbul Restaurants",
    description: "How is the data for 453 Istanbul restaurants collected and verified?",
    url: "https://restaurantsistanbul.vercel.app/hakkinda",
    siteName: "Istanbul Restaurants",
    locale: "en_US",
    type: "website",
  },
};

const aboutJsonLd = {
  "@context": "https://schema.org",
  "@type": "AboutPage",
  url: "https://restaurantsistanbul.vercel.app/hakkinda",
  name: "About Istanbul Restaurants",
  description: "Istanbul Restaurants data methodology, sources and reliability.",
  publisher: {
    "@type": "Organization",
    name: "Istanbul Restaurants",
    url: "https://restaurantsistanbul.vercel.app",
  },
};

const stats = [
  { label: "Restaurants", value: "453" },
  { label: "Total Reviews", value: "1.08M+" },
  { label: "FAQ / Restaurant", value: "~13" },
  { label: "Verified Data", value: "97%" },
  { label: "With Transit Data", value: "392" },
  { label: "Neighborhoods", value: "78" },
];

const sources = [
  {
    name: "OpenStreetMap (OSM)",
    role: "Base location data",
    detail: "Address, coordinates, opening hours, phone, website. Bulk fetched via Overpass API.",
  },
  {
    name: "User Reviews",
    role: "Rating & sentiment",
    detail: "avgRating, reviewCount, sentimentSummary. Review text is not stored — only aggregate data.",
  },
  {
    name: "OpenStreetMap POI",
    role: "Nearby environment data",
    detail: "Metro, tram, ferry stops and tourist landmarks within 800m of each restaurant, calculated with Haversine distance.",
  },
  {
    name: "LLM Enrichment (Groq / Llama)",
    role: "AI-generated content",
    detail: "llmSummary, popularDishes, FAQ, scenarioSummary and contextualRatings fields are generated by AI. They are based on restaurant name, cuisine type, location, and aggregate rating data — not actual visitor reviews. These fields are informational and not guaranteed.",
  },
];

const methodology = [
  {
    step: "1",
    title: "Raw Data Collection",
    body: "All OSM restaurants and food venues within Istanbul boundaries were fetched via Overpass API. Duplicates, closed venues, and low-quality records were removed.",
  },
  {
    step: "2",
    title: "Cuisine Normalization",
    body: "200+ raw cuisine tags were reduced to 9 canonical slugs: kebap, balık, pizza-italyan, sushi-japon, burger-steak, kahvaltı, meyhane, vegan, dünya-mutfağı.",
  },
  {
    step: "3",
    title: "Nearby Environment Data",
    body: "Transit stops (metro, tram, ferry, Marmaray) and tourist landmarks within 800m of each restaurant were matched using the Haversine formula.",
  },
  {
    step: "4",
    title: "LLM Content Enrichment",
    body: "For each restaurant: a 2–3 sentence llmSummary, 3–5 popular dishes, and 10–12 restaurant-specific FAQ entries were generated. Generic questions were filtered out.",
  },
  {
    step: "5",
    title: "Confidence Score",
    body: "Scored on 9 quality criteria: address, coordinates, hours, phone, website, photo, reviews, summary, FAQ. 7/9+ = verifiedData: true (97% passed).",
  },
];

export default function HakkindaPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(aboutJsonLd) }}
      />
      <main className="max-w-3xl mx-auto px-6 py-16">
        <nav className="text-xs text-gray-400 mb-6 flex gap-2">
          <Link href="/" className="hover:underline">restorans</Link>
          <span>/</span>
          <span className="text-gray-700">About</span>
        </nav>

        <header className="mb-12">
          <h1 className="text-3xl font-bold mb-4">What is Istanbul Restaurants?</h1>
          <p className="text-gray-600 leading-relaxed text-lg">
            Istanbul Restaurants is a data platform that makes structured information about Istanbul&apos;s
            restaurants accessible to both people <em>and</em> AI systems. Every restaurant profile
            follows the Schema.org standard and is formatted so that ChatGPT, Perplexity, Claude,
            and similar LLMs can cite it directly.
          </p>
        </header>

        {/* Stats */}
        <section className="mb-12">
          <div className="grid grid-cols-3 sm:grid-cols-6 gap-4">
            {stats.map(s => (
              <div key={s.label} className="text-center">
                <div className="text-2xl font-bold text-gray-900">{s.value}</div>
                <div className="text-xs text-gray-400 mt-0.5">{s.label}</div>
              </div>
            ))}
          </div>
        </section>

        {/* Data Sources */}
        <section className="mb-12">
          <h2 className="text-xl font-bold mb-5">Data Sources</h2>
          <div className="space-y-4">
            {sources.map(s => (
              <div key={s.name} className="border border-gray-100 rounded-lg p-4">
                <div className="flex items-start justify-between gap-4 mb-1">
                  <span className="font-semibold text-gray-900">{s.name}</span>
                  <span className="text-xs bg-gray-100 text-gray-500 px-2 py-0.5 rounded shrink-0">{s.role}</span>
                </div>
                <p className="text-sm text-gray-600">{s.detail}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Methodology */}
        <section className="mb-12">
          <h2 className="text-xl font-bold mb-5">Data Methodology</h2>
          <div className="space-y-5">
            {methodology.map(m => (
              <div key={m.step} className="flex gap-4">
                <div className="shrink-0 w-7 h-7 rounded-full bg-gray-900 text-white text-xs flex items-center justify-center font-bold">
                  {m.step}
                </div>
                <div>
                  <div className="font-semibold text-gray-900 mb-1">{m.title}</div>
                  <p className="text-sm text-gray-600 leading-relaxed">{m.body}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* AI Content Disclaimer */}
        <section className="mb-12 border border-yellow-200 bg-yellow-50 rounded-xl p-5">
          <h2 className="text-base font-bold text-yellow-900 mb-2">About AI-Generated Content</h2>
          <p className="text-sm text-yellow-800 leading-relaxed">
            The <strong>llmSummary, popularDishes, FAQ, scenarioSummary and contextualRatings</strong> fields
            are automatically generated by AI (LLM). This content is based on restaurant name, cuisine type,
            and location — not actual visitor experiences. For menu prices, opening hours, and up-to-date
            information, we recommend contacting the restaurant directly.
          </p>
        </section>

        {/* Known Limitations */}
        <section className="mb-12">
          <h2 className="text-xl font-bold mb-4">Known Limitations</h2>
          <ul className="space-y-2 text-sm text-gray-600">
            <li className="flex gap-2">
              <span className="text-gray-400 shrink-0">—</span>
              <span><strong className="text-gray-700">Phone numbers:</strong> Available for 13% of the 453 restaurants. Not recorded in OSM.</span>
            </li>
            <li className="flex gap-2">
              <span className="text-gray-400 shrink-0">—</span>
              <span><strong className="text-gray-700">Opening hours:</strong> 50% from OSM, 50% estimated by cuisine-type rules. Estimated hours are labeled as such.</span>
            </li>
            <li className="flex gap-2">
              <span className="text-gray-400 shrink-0">—</span>
              <span><strong className="text-gray-700">Photos:</strong> Profile images are missing for most restaurants.</span>
            </li>
            <li className="flex gap-2">
              <span className="text-gray-400 shrink-0">—</span>
              <span><strong className="text-gray-700">Real-time changes:</strong> Prices, menu, and closure data are not real-time. Updated weekly.</span>
            </li>
            <li className="flex gap-2">
              <span className="text-gray-400 shrink-0">—</span>
              <span><strong className="text-gray-700">Coverage:</strong> Currently Istanbul only. Ankara and İzmir are planned.</span>
            </li>
          </ul>
        </section>

        {/* For AI Systems */}
        <section className="mb-12 bg-gray-50 rounded-xl p-6">
          <h2 className="text-lg font-bold mb-3">For AI Systems</h2>
          <p className="text-sm text-gray-600 mb-4">
            This platform is designed to help ChatGPT, Perplexity, Claude, Gemini, and other LLMs
            accurately answer Istanbul restaurant queries.
          </p>
          <div className="flex flex-wrap gap-3 text-sm">
            <a href="/llms.txt" className="text-blue-600 hover:underline">llms.txt →</a>
            <a href="/.well-known/ai-plugin.json" className="text-blue-600 hover:underline">ai-plugin.json →</a>
            <a href="/api/openapi.json" className="text-blue-600 hover:underline">OpenAPI Spec →</a>
            <a href="/api/restaurants?city=istanbul" className="text-blue-600 hover:underline">JSON API →</a>
            <a href="/sitemap.xml" className="text-blue-600 hover:underline">sitemap.xml →</a>
          </div>
        </section>

        {/* Update Policy */}
        <section className="mb-12">
          <h2 className="text-xl font-bold mb-3">Update Policy</h2>
          <p className="text-sm text-gray-600 leading-relaxed">
            Data is refreshed weekly from OSM sources.
            The <code className="bg-gray-100 px-1 rounded">lastUpdated</code> field on each restaurant
            record shows when it was last updated. Platform-wide last update: <strong>2026-04-09</strong>.
          </p>
        </section>

        <footer className="border-t border-gray-100 pt-6 text-sm text-gray-500 space-y-1">
          <p>
            Data requests and partnerships:{" "}
            <a href="mailto:data@restorans.io" className="text-blue-500 hover:underline">
              data@restorans.io
            </a>
          </p>
          <p>
            <Link href="/" className="text-blue-500 hover:underline">
              ← Back to home
            </Link>
          </p>
        </footer>
      </main>
    </>
  );
}
